on:
  push:
    branches:
      - testing

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: pineapple-lab/jira-issue-transitions@v1.3
        with:
          who-to-greet: 'MyName isTheBest'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"